import './styles/vuetify.scss';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import '@fontsource/inter/400.css';
import '@fontsource/inter/600.css';
import '@fontsource/noto-sans/400.css';
import '@fontsource/noto-sans/600.css';
import '@mdi/font/css/materialdesignicons.css';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import { createApp } from 'vue';
import App from './App.vue';
import { ErrorType } from './enums/errorType.enum.mts';
import { ErrorHandler } from './errors/errorHandler.mts';
import { router } from './plugins/router.mjs';
import { vuetify } from './plugins/vuetify.mjs';

const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
const app = createApp(App);
app.use(vuetify);
app.use(router);
app.use(pinia);
app.config.errorHandler = ErrorHandler.handleViteErrors.bind(ErrorHandler);
window.addEventListener(ErrorType.Error, ErrorHandler.handleError.bind(ErrorHandler));
window.addEventListener(ErrorType.UnhandledRejection, ErrorHandler.handleUnhandleRejections.bind(ErrorHandler));
app.mount('#app');
